#! /bin/sh
set -eu

# Это ожидаемая точка входа для Cockpit CI; будет вызываться без
# аргументы, но с соответствующим $ TEST_OS и, необязательно, $ TEST_SCENARIO

[ -z "${TEST_SCENARIO:-}" ] || export TEST_BROWSER="$TEST_SCENARIO"
make check
