#!/bin/sh
# сценарий настройки изображения для включения кабины в тестовых виртуальных машинах
# RPM приложения будут установлены отдельно
set -eu

# не форсируйте https: // (самоподписанный сертификат)
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

if type firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --add-service=cockpit --permanent
fi
systemctl enable cockpit.socket

# HACK: см. https://github.com/cockpit-project/cockpit/issues/14133
mkdir -p /usr/share/cockpit/packagekit
